// Каталоги товаров (данные) — вынесены из бывших экранов-магазинов, которые
// были заменены на ShopTab/MarketTab и удалены. Используются только редактором
// цен (PriceEditorTab) как справочник позиций. Цены (`price: null`) приходят с
// сервера; здесь только метаданные позиций.

export const GPU_PRODUCTS = [
  { id: 1, name: 'CrystalCore Quartz Q320', hashrate: 180, price: null, company: 'CrystalCore', line: 'Quartz' },
  { id: 2, name: 'CrystalCore Quartz Q340', hashrate: 220, price: null, company: 'CrystalCore', line: 'Quartz' },
  { id: 3, name: 'CrystalCore Quartz Q360', hashrate: 270, price: null, company: 'CrystalCore', line: 'Quartz' },
  { id: 4, name: 'CrystalCore Quartz Q380', hashrate: 330, price: null, company: 'CrystalCore', line: 'Quartz' },
  { id: 5, name: 'CrystalCore Quartz Q400', hashrate: 400, price: null, company: 'CrystalCore', line: 'Quartz' },
  { id: 6, name: 'CrystalCore Quartz Q420', hashrate: 480, price: null, company: 'CrystalCore', line: 'Quartz' },
  { id: 7, name: 'CrystalCore Topaz T520', hashrate: 620, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 8, name: 'CrystalCore Topaz T540', hashrate: 760, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 9, name: 'CrystalCore Topaz T560', hashrate: 930, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 10, name: 'CrystalCore Topaz T580', hashrate: 1120, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 11, name: 'CrystalCore Topaz T600', hashrate: 1340, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 12, name: 'CrystalCore Topaz T620', hashrate: 1600, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 13, name: 'CrystalCore Topaz T640', hashrate: 1900, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 14, name: 'CrystalCore Topaz T660', hashrate: 2250, price: null, company: 'CrystalCore', line: 'Topaz' },
  { id: 15, name: 'CrystalCore Sapphire S720', hashrate: 2700, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 16, name: 'CrystalCore Sapphire S740', hashrate: 3150, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 17, name: 'CrystalCore Sapphire S760', hashrate: 3650, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 18, name: 'CrystalCore Sapphire S780', hashrate: 4200, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 19, name: 'CrystalCore Sapphire S800', hashrate: 4850, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 20, name: 'CrystalCore Sapphire S820', hashrate: 5600, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 21, name: 'CrystalCore Sapphire S840', hashrate: 6450, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 22, name: 'CrystalCore Sapphire S860', hashrate: 7350, price: null, company: 'CrystalCore', line: 'Sapphire' },
  { id: 23, name: 'CrystalCore Diamond D920', hashrate: 8400, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 24, name: 'CrystalCore Diamond D940', hashrate: 9600, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 25, name: 'CrystalCore Diamond D960', hashrate: 11000, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 26, name: 'CrystalCore Diamond D980', hashrate: 12500, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 27, name: 'CrystalCore Diamond D1000', hashrate: 14200, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 28, name: 'CrystalCore Diamond D1020', hashrate: 16000, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 29, name: 'CrystalCore Diamond D1040', hashrate: 18000, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 30, name: 'CrystalCore Diamond D1060', hashrate: 20000, price: null, company: 'CrystalCore', line: 'Diamond' },
  { id: 31, name: 'Pyronix Spark SP320', hashrate: 210, price: null, company: 'Pyronix', line: 'Spark' },
  { id: 32, name: 'Pyronix Spark SP340', hashrate: 260, price: null, company: 'Pyronix', line: 'Spark' },
  { id: 33, name: 'Pyronix Spark SP360', hashrate: 320, price: null, company: 'Pyronix', line: 'Spark' },
  { id: 34, name: 'Pyronix Spark SP380', hashrate: 390, price: null, company: 'Pyronix', line: 'Spark' },
  { id: 35, name: 'Pyronix Spark SP400', hashrate: 470, price: null, company: 'Pyronix', line: 'Spark' },
  { id: 36, name: 'Pyronix Spark SP420', hashrate: 560, price: null, company: 'Pyronix', line: 'Spark' },
  { id: 37, name: 'Pyronix Flare FL520', hashrate: 720, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 38, name: 'Pyronix Flare FL540', hashrate: 880, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 39, name: 'Pyronix Flare FL560', hashrate: 1070, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 40, name: 'Pyronix Flare FL580', hashrate: 1290, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 41, name: 'Pyronix Flare FL600', hashrate: 1550, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 42, name: 'Pyronix Flare FL620', hashrate: 1860, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 43, name: 'Pyronix Flare FL640', hashrate: 2220, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 44, name: 'Pyronix Flare FL660', hashrate: 2650, price: null, company: 'Pyronix', line: 'Flare' },
  { id: 45, name: 'Pyronix Blaze BZ720', hashrate: 3150, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 46, name: 'Pyronix Blaze BZ740', hashrate: 3700, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 47, name: 'Pyronix Blaze BZ760', hashrate: 4350, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 48, name: 'Pyronix Blaze BZ780', hashrate: 5100, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 49, name: 'Pyronix Blaze BZ800', hashrate: 5950, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 50, name: 'Pyronix Blaze BZ820', hashrate: 6900, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 51, name: 'Pyronix Blaze BZ840', hashrate: 8000, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 52, name: 'Pyronix Blaze BZ860', hashrate: 9250, price: null, company: 'Pyronix', line: 'Blaze' },
  { id: 53, name: 'Pyronix Inferno IF920', hashrate: 10700, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 54, name: 'Pyronix Inferno IF940', hashrate: 12300, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 55, name: 'Pyronix Inferno IF960', hashrate: 14100, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 56, name: 'Pyronix Inferno IF980', hashrate: 16200, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 57, name: 'Pyronix Inferno IF1000', hashrate: 18500, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 58, name: 'Pyronix Inferno IF1020', hashrate: 21000, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 59, name: 'Pyronix Inferno IF1040', hashrate: 24000, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 60, name: 'Pyronix Inferno IF1060', hashrate: 27000, price: null, company: 'Pyronix', line: 'Inferno' },
  { id: 61, name: 'Archivex Vault V320', hashrate: 170, price: null, company: 'Archivex', line: 'Vault' },
  { id: 62, name: 'Archivex Vault V340', hashrate: 210, price: null, company: 'Archivex', line: 'Vault' },
  { id: 63, name: 'Archivex Vault V360', hashrate: 260, price: null, company: 'Archivex', line: 'Vault' },
  { id: 64, name: 'Archivex Vault V380', hashrate: 320, price: null, company: 'Archivex', line: 'Vault' },
  { id: 65, name: 'Archivex Vault V400', hashrate: 390, price: null, company: 'Archivex', line: 'Vault' },
  { id: 66, name: 'Archivex Vault V420', hashrate: 470, price: null, company: 'Archivex', line: 'Vault' },
  { id: 67, name: 'Archivex Legacy L520', hashrate: 600, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 68, name: 'Archivex Legacy L540', hashrate: 730, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 69, name: 'Archivex Legacy L560', hashrate: 890, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 70, name: 'Archivex Legacy L580', hashrate: 1070, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 71, name: 'Archivex Legacy L600', hashrate: 1290, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 72, name: 'Archivex Legacy L620', hashrate: 1550, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 73, name: 'Archivex Legacy L640', hashrate: 1860, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 74, name: 'Archivex Legacy L660', hashrate: 2220, price: null, company: 'Archivex', line: 'Legacy' },
  { id: 75, name: 'Archivex Archive A720', hashrate: 2650, price: null, company: 'Archivex', line: 'Archive' },
  { id: 76, name: 'Archivex Archive A740', hashrate: 3150, price: null, company: 'Archivex', line: 'Archive' },
  { id: 77, name: 'Archivex Archive A760', hashrate: 3700, price: null, company: 'Archivex', line: 'Archive' },
  { id: 78, name: 'Archivex Archive A780', hashrate: 4350, price: null, company: 'Archivex', line: 'Archive' },
  { id: 79, name: 'Archivex Archive A800', hashrate: 5100, price: null, company: 'Archivex', line: 'Archive' },
  { id: 80, name: 'Archivex Archive A820', hashrate: 5950, price: null, company: 'Archivex', line: 'Archive' },
  { id: 81, name: 'Archivex Archive A840', hashrate: 6900, price: null, company: 'Archivex', line: 'Archive' },
  { id: 82, name: 'Archivex Archive A860', hashrate: 8000, price: null, company: 'Archivex', line: 'Archive' },
  { id: 83, name: 'Archivex Genesis G920', hashrate: 9300, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 84, name: 'Archivex Genesis G940', hashrate: 10800, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 85, name: 'Archivex Genesis G960', hashrate: 12500, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 86, name: 'Archivex Genesis G980', hashrate: 14500, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 87, name: 'Archivex Genesis G1000', hashrate: 16700, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 88, name: 'Archivex Genesis G1020', hashrate: 19200, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 89, name: 'Archivex Genesis G1040', hashrate: 22000, price: null, company: 'Archivex', line: 'Genesis' },
  { id: 90, name: 'Archivex Genesis G1060', hashrate: 25000, price: null, company: 'Archivex', line: 'Genesis' },
]

export const CPU_PRODUCTS = [
  { id: 1, name: 'CrystalChip Stone S210', maxGpus: 1, multiplier: 1.00, price: null, company: 'CrystalChip', line: 'Stone' },
  { id: 2, name: 'CrystalChip Stone S220', maxGpus: 2, multiplier: 1.01, price: null, company: 'CrystalChip', line: 'Stone' },
  { id: 3, name: 'CrystalChip Stone S230', maxGpus: 2, multiplier: 1.02, price: null, company: 'CrystalChip', line: 'Stone' },
  { id: 4, name: 'CrystalChip Stone S240', maxGpus: 3, multiplier: 1.03, price: null, company: 'CrystalChip', line: 'Stone' },
  { id: 5, name: 'CrystalChip Stone S250', maxGpus: 4, multiplier: 1.04, price: null, company: 'CrystalChip', line: 'Stone' },
  { id: 6, name: 'CrystalChip Stone S260', maxGpus: 5, multiplier: 1.05, price: null, company: 'CrystalChip', line: 'Stone' },
  { id: 7, name: 'CrystalChip Crystal C310', maxGpus: 6, multiplier: 1.07, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 8, name: 'CrystalChip Crystal C320', maxGpus: 7, multiplier: 1.09, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 9, name: 'CrystalChip Crystal C330', maxGpus: 8, multiplier: 1.11, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 10, name: 'CrystalChip Crystal C340', maxGpus: 9, multiplier: 1.13, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 11, name: 'CrystalChip Crystal C350', maxGpus: 10, multiplier: 1.15, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 12, name: 'CrystalChip Crystal C360', maxGpus: 11, multiplier: 1.17, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 13, name: 'CrystalChip Crystal C370', maxGpus: 12, multiplier: 1.19, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 14, name: 'CrystalChip Crystal C380', maxGpus: 13, multiplier: 1.21, price: null, company: 'CrystalChip', line: 'Crystal' },
  { id: 15, name: 'CrystalChip Diamond D410', maxGpus: 14, multiplier: 1.24, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 16, name: 'CrystalChip Diamond D420', maxGpus: 15, multiplier: 1.27, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 17, name: 'CrystalChip Diamond D430', maxGpus: 16, multiplier: 1.30, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 18, name: 'CrystalChip Diamond D440', maxGpus: 17, multiplier: 1.33, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 19, name: 'CrystalChip Diamond D450', maxGpus: 18, multiplier: 1.36, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 20, name: 'CrystalChip Diamond D460', maxGpus: 19, multiplier: 1.39, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 21, name: 'CrystalChip Diamond D470', maxGpus: 20, multiplier: 1.42, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 22, name: 'CrystalChip Diamond D480', maxGpus: 21, multiplier: 1.45, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 23, name: 'CrystalChip Diamond D490', maxGpus: 22, multiplier: 1.48, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 24, name: 'CrystalChip Diamond D500', maxGpus: 23, multiplier: 1.52, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 25, name: 'CrystalChip Diamond D510', maxGpus: 24, multiplier: 1.56, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 26, name: 'CrystalChip Diamond D520', maxGpus: 25, multiplier: 1.60, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 27, name: 'CrystalChip Diamond D530', maxGpus: 26, multiplier: 1.65, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 28, name: 'CrystalChip Diamond D540', maxGpus: 27, multiplier: 1.70, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 29, name: 'CrystalChip Diamond D550', maxGpus: 28, multiplier: 1.75, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 30, name: 'CrystalChip Diamond D560', maxGpus: 30, multiplier: 1.80, price: null, company: 'CrystalChip', line: 'Diamond' },
  { id: 31, name: 'PyroCore Ember E210', maxGpus: 2, multiplier: 1.02, price: null, company: 'PyroCore', line: 'Ember' },
  { id: 32, name: 'PyroCore Ember E220', maxGpus: 3, multiplier: 1.03, price: null, company: 'PyroCore', line: 'Ember' },
  { id: 33, name: 'PyroCore Ember E230', maxGpus: 4, multiplier: 1.05, price: null, company: 'PyroCore', line: 'Ember' },
  { id: 34, name: 'PyroCore Ember E240', maxGpus: 5, multiplier: 1.07, price: null, company: 'PyroCore', line: 'Ember' },
  { id: 35, name: 'PyroCore Ember E250', maxGpus: 6, multiplier: 1.09, price: null, company: 'PyroCore', line: 'Ember' },
  { id: 36, name: 'PyroCore Ember E260', maxGpus: 7, multiplier: 1.11, price: null, company: 'PyroCore', line: 'Ember' },
  { id: 37, name: 'PyroCore Blaze B310', maxGpus: 8, multiplier: 1.14, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 38, name: 'PyroCore Blaze B320', maxGpus: 9, multiplier: 1.17, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 39, name: 'PyroCore Blaze B330', maxGpus: 10, multiplier: 1.20, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 40, name: 'PyroCore Blaze B340', maxGpus: 11, multiplier: 1.23, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 41, name: 'PyroCore Blaze B350', maxGpus: 12, multiplier: 1.26, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 42, name: 'PyroCore Blaze B360', maxGpus: 13, multiplier: 1.29, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 43, name: 'PyroCore Blaze B370', maxGpus: 14, multiplier: 1.32, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 44, name: 'PyroCore Blaze B380', maxGpus: 15, multiplier: 1.35, price: null, company: 'PyroCore', line: 'Blaze' },
  { id: 45, name: 'PyroCore Inferno I410', maxGpus: 16, multiplier: 1.39, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 46, name: 'PyroCore Inferno I420', maxGpus: 17, multiplier: 1.43, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 47, name: 'PyroCore Inferno I430', maxGpus: 18, multiplier: 1.47, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 48, name: 'PyroCore Inferno I440', maxGpus: 19, multiplier: 1.51, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 49, name: 'PyroCore Inferno I450', maxGpus: 20, multiplier: 1.55, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 50, name: 'PyroCore Inferno I460', maxGpus: 21, multiplier: 1.59, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 51, name: 'PyroCore Inferno I470', maxGpus: 22, multiplier: 1.63, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 52, name: 'PyroCore Inferno I480', maxGpus: 23, multiplier: 1.67, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 53, name: 'PyroCore Inferno I490', maxGpus: 24, multiplier: 1.72, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 54, name: 'PyroCore Inferno I500', maxGpus: 25, multiplier: 1.77, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 55, name: 'PyroCore Inferno I510', maxGpus: 26, multiplier: 1.82, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 56, name: 'PyroCore Inferno I520', maxGpus: 27, multiplier: 1.87, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 57, name: 'PyroCore Inferno I530', maxGpus: 28, multiplier: 1.92, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 58, name: 'PyroCore Inferno I540', maxGpus: 29, multiplier: 1.97, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 59, name: 'PyroCore Inferno I550', maxGpus: 30, multiplier: 2.03, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 60, name: 'PyroCore Inferno I560', maxGpus: 32, multiplier: 2.10, price: null, company: 'PyroCore', line: 'Inferno' },
  { id: 61, name: 'ArchiveCore Legacy L210', maxGpus: 1, multiplier: 1.01, price: null, company: 'ArchiveCore', line: 'Legacy' },
  { id: 62, name: 'ArchiveCore Legacy L220', maxGpus: 2, multiplier: 1.02, price: null, company: 'ArchiveCore', line: 'Legacy' },
  { id: 63, name: 'ArchiveCore Legacy L230', maxGpus: 3, multiplier: 1.03, price: null, company: 'ArchiveCore', line: 'Legacy' },
  { id: 64, name: 'ArchiveCore Legacy L240', maxGpus: 4, multiplier: 1.05, price: null, company: 'ArchiveCore', line: 'Legacy' },
  { id: 65, name: 'ArchiveCore Legacy L250', maxGpus: 5, multiplier: 1.07, price: null, company: 'ArchiveCore', line: 'Legacy' },
  { id: 66, name: 'ArchiveCore Legacy L260', maxGpus: 6, multiplier: 1.09, price: null, company: 'ArchiveCore', line: 'Legacy' },
  { id: 67, name: 'ArchiveCore Archive A310', maxGpus: 7, multiplier: 1.11, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 68, name: 'ArchiveCore Archive A320', maxGpus: 8, multiplier: 1.13, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 69, name: 'ArchiveCore Archive A330', maxGpus: 9, multiplier: 1.15, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 70, name: 'ArchiveCore Archive A340', maxGpus: 10, multiplier: 1.17, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 71, name: 'ArchiveCore Archive A350', maxGpus: 11, multiplier: 1.19, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 72, name: 'ArchiveCore Archive A360', maxGpus: 12, multiplier: 1.21, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 73, name: 'ArchiveCore Archive A370', maxGpus: 13, multiplier: 1.23, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 74, name: 'ArchiveCore Archive A380', maxGpus: 14, multiplier: 1.25, price: null, company: 'ArchiveCore', line: 'Archive' },
  { id: 75, name: 'ArchiveCore Genesis G410', maxGpus: 15, multiplier: 1.28, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 76, name: 'ArchiveCore Genesis G420', maxGpus: 16, multiplier: 1.31, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 77, name: 'ArchiveCore Genesis G430', maxGpus: 17, multiplier: 1.34, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 78, name: 'ArchiveCore Genesis G440', maxGpus: 18, multiplier: 1.37, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 79, name: 'ArchiveCore Genesis G450', maxGpus: 19, multiplier: 1.40, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 80, name: 'ArchiveCore Genesis G460', maxGpus: 20, multiplier: 1.43, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 81, name: 'ArchiveCore Genesis G470', maxGpus: 21, multiplier: 1.46, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 82, name: 'ArchiveCore Genesis G480', maxGpus: 22, multiplier: 1.49, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 83, name: 'ArchiveCore Genesis G490', maxGpus: 23, multiplier: 1.53, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 84, name: 'ArchiveCore Genesis G500', maxGpus: 24, multiplier: 1.57, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 85, name: 'ArchiveCore Genesis G510', maxGpus: 25, multiplier: 1.61, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 86, name: 'ArchiveCore Genesis G520', maxGpus: 26, multiplier: 1.65, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 87, name: 'ArchiveCore Genesis G530', maxGpus: 27, multiplier: 1.70, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 88, name: 'ArchiveCore Genesis G540', maxGpus: 28, multiplier: 1.75, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 89, name: 'ArchiveCore Genesis G550', maxGpus: 29, multiplier: 1.80, price: null, company: 'ArchiveCore', line: 'Genesis' },
  { id: 90, name: 'ArchiveCore Genesis G560', maxGpus: 30, multiplier: 1.85, price: null, company: 'ArchiveCore', line: 'Genesis' },
]

export const CASE_PRODUCTS = [
  { id: 1, name: 'TitanFrame Mini M100', maxGpus: 1, price: null, company: 'TitanFrame', line: 'Mini' },
  { id: 2, name: 'TitanFrame Mini M110', maxGpus: 1, price: null, company: 'TitanFrame', line: 'Mini' },
  { id: 3, name: 'TitanFrame Mini M120', maxGpus: 2, price: null, company: 'TitanFrame', line: 'Mini' },
  { id: 4, name: 'TitanFrame Mini M130', maxGpus: 2, price: null, company: 'TitanFrame', line: 'Mini' },
  { id: 5, name: 'TitanFrame Mini M140', maxGpus: 3, price: null, company: 'TitanFrame', line: 'Mini' },
  { id: 6, name: 'TitanFrame Mini M150', maxGpus: 3, price: null, company: 'TitanFrame', line: 'Mini' },
  { id: 7, name: 'TitanFrame Air A200', maxGpus: 4, price: null, company: 'TitanFrame', line: 'Air' },
  { id: 8, name: 'TitanFrame Air A210', maxGpus: 4, price: null, company: 'TitanFrame', line: 'Air' },
  { id: 9, name: 'TitanFrame Air A220', maxGpus: 5, price: null, company: 'TitanFrame', line: 'Air' },
  { id: 10, name: 'TitanFrame Air A230', maxGpus: 5, price: null, company: 'TitanFrame', line: 'Air' },
  { id: 11, name: 'TitanFrame Air A240', maxGpus: 6, price: null, company: 'TitanFrame', line: 'Air' },
  { id: 12, name: 'TitanFrame Air A250', maxGpus: 6, price: null, company: 'TitanFrame', line: 'Air' },
  { id: 13, name: 'TitanFrame Pro P300', maxGpus: 7, price: null, company: 'TitanFrame', line: 'Pro' },
  { id: 14, name: 'TitanFrame Pro P310', maxGpus: 8, price: null, company: 'TitanFrame', line: 'Pro' },
  { id: 15, name: 'TitanFrame Pro P320', maxGpus: 9, price: null, company: 'TitanFrame', line: 'Pro' },
  { id: 16, name: 'TitanFrame Pro P330', maxGpus: 10, price: null, company: 'TitanFrame', line: 'Pro' },
  { id: 17, name: 'TitanFrame Pro P340', maxGpus: 11, price: null, company: 'TitanFrame', line: 'Pro' },
  { id: 18, name: 'TitanFrame Pro P350', maxGpus: 12, price: null, company: 'TitanFrame', line: 'Pro' },
  { id: 19, name: 'TitanFrame Ultra U400', maxGpus: 13, price: null, company: 'TitanFrame', line: 'Ultra' },
  { id: 20, name: 'TitanFrame Ultra U410', maxGpus: 14, price: null, company: 'TitanFrame', line: 'Ultra' },
  { id: 21, name: 'TitanFrame Ultra U420', maxGpus: 15, price: null, company: 'TitanFrame', line: 'Ultra' },
  { id: 22, name: 'TitanFrame Ultra U430', maxGpus: 16, price: null, company: 'TitanFrame', line: 'Ultra' },
  { id: 23, name: 'TitanFrame Ultra U440', maxGpus: 17, price: null, company: 'TitanFrame', line: 'Ultra' },
  { id: 24, name: 'TitanFrame Ultra U450', maxGpus: 18, price: null, company: 'TitanFrame', line: 'Ultra' },
  { id: 25, name: 'TitanFrame Titan T500', maxGpus: 19, price: null, company: 'TitanFrame', line: 'Titan' },
  { id: 26, name: 'TitanFrame Titan T510', maxGpus: 20, price: null, company: 'TitanFrame', line: 'Titan' },
  { id: 27, name: 'TitanFrame Titan T520', maxGpus: 22, price: null, company: 'TitanFrame', line: 'Titan' },
  { id: 28, name: 'TitanFrame Titan T530', maxGpus: 24, price: null, company: 'TitanFrame', line: 'Titan' },
  { id: 29, name: 'TitanFrame Titan T540', maxGpus: 27, price: null, company: 'TitanFrame', line: 'Titan' },
  { id: 30, name: 'TitanFrame Titan T550', maxGpus: 30, price: null, company: 'TitanFrame', line: 'Titan' },
  { id: 31, name: 'NovaCase Nano N100', maxGpus: 1, price: null, company: 'NovaCase', line: 'Nano' },
  { id: 32, name: 'NovaCase Nano N110', maxGpus: 1, price: null, company: 'NovaCase', line: 'Nano' },
  { id: 33, name: 'NovaCase Nano N120', maxGpus: 2, price: null, company: 'NovaCase', line: 'Nano' },
  { id: 34, name: 'NovaCase Nano N130', maxGpus: 2, price: null, company: 'NovaCase', line: 'Nano' },
  { id: 35, name: 'NovaCase Nano N140', maxGpus: 3, price: null, company: 'NovaCase', line: 'Nano' },
  { id: 36, name: 'NovaCase Nano N150', maxGpus: 4, price: null, company: 'NovaCase', line: 'Nano' },
  { id: 37, name: 'NovaCase Flow F200', maxGpus: 4, price: null, company: 'NovaCase', line: 'Flow' },
  { id: 38, name: 'NovaCase Flow F210', maxGpus: 5, price: null, company: 'NovaCase', line: 'Flow' },
  { id: 39, name: 'NovaCase Flow F220', maxGpus: 5, price: null, company: 'NovaCase', line: 'Flow' },
  { id: 40, name: 'NovaCase Flow F230', maxGpus: 6, price: null, company: 'NovaCase', line: 'Flow' },
  { id: 41, name: 'NovaCase Flow F240', maxGpus: 6, price: null, company: 'NovaCase', line: 'Flow' },
  { id: 42, name: 'NovaCase Flow F250', maxGpus: 7, price: null, company: 'NovaCase', line: 'Flow' },
  { id: 43, name: 'NovaCase Prime P300', maxGpus: 8, price: null, company: 'NovaCase', line: 'Prime' },
  { id: 44, name: 'NovaCase Prime P310', maxGpus: 9, price: null, company: 'NovaCase', line: 'Prime' },
  { id: 45, name: 'NovaCase Prime P320', maxGpus: 10, price: null, company: 'NovaCase', line: 'Prime' },
  { id: 46, name: 'NovaCase Prime P330', maxGpus: 11, price: null, company: 'NovaCase', line: 'Prime' },
  { id: 47, name: 'NovaCase Prime P340', maxGpus: 12, price: null, company: 'NovaCase', line: 'Prime' },
  { id: 48, name: 'NovaCase Prime P350', maxGpus: 13, price: null, company: 'NovaCase', line: 'Prime' },
  { id: 49, name: 'NovaCase Elite E400', maxGpus: 14, price: null, company: 'NovaCase', line: 'Elite' },
  { id: 50, name: 'NovaCase Elite E410', maxGpus: 15, price: null, company: 'NovaCase', line: 'Elite' },
  { id: 51, name: 'NovaCase Elite E420', maxGpus: 16, price: null, company: 'NovaCase', line: 'Elite' },
  { id: 52, name: 'NovaCase Elite E430', maxGpus: 17, price: null, company: 'NovaCase', line: 'Elite' },
  { id: 53, name: 'NovaCase Elite E440', maxGpus: 18, price: null, company: 'NovaCase', line: 'Elite' },
  { id: 54, name: 'NovaCase Elite E450', maxGpus: 19, price: null, company: 'NovaCase', line: 'Elite' },
  { id: 55, name: 'NovaCase Apex X500', maxGpus: 20, price: null, company: 'NovaCase', line: 'Apex' },
  { id: 56, name: 'NovaCase Apex X510', maxGpus: 22, price: null, company: 'NovaCase', line: 'Apex' },
  { id: 57, name: 'NovaCase Apex X520', maxGpus: 24, price: null, company: 'NovaCase', line: 'Apex' },
  { id: 58, name: 'NovaCase Apex X530', maxGpus: 26, price: null, company: 'NovaCase', line: 'Apex' },
  { id: 59, name: 'NovaCase Apex X540', maxGpus: 28, price: null, company: 'NovaCase', line: 'Apex' },
  { id: 60, name: 'NovaCase Apex X550', maxGpus: 30, price: null, company: 'NovaCase', line: 'Apex' },
  { id: 61, name: 'IronNest Base B100', maxGpus: 1, price: null, company: 'IronNest', line: 'Base' },
  { id: 62, name: 'IronNest Base B110', maxGpus: 2, price: null, company: 'IronNest', line: 'Base' },
  { id: 63, name: 'IronNest Base B120', maxGpus: 2, price: null, company: 'IronNest', line: 'Base' },
  { id: 64, name: 'IronNest Base B130', maxGpus: 3, price: null, company: 'IronNest', line: 'Base' },
  { id: 65, name: 'IronNest Base B140', maxGpus: 3, price: null, company: 'IronNest', line: 'Base' },
  { id: 66, name: 'IronNest Base B150', maxGpus: 4, price: null, company: 'IronNest', line: 'Base' },
  { id: 67, name: 'IronNest Forge F200', maxGpus: 4, price: null, company: 'IronNest', line: 'Forge' },
  { id: 68, name: 'IronNest Forge F210', maxGpus: 5, price: null, company: 'IronNest', line: 'Forge' },
  { id: 69, name: 'IronNest Forge F220', maxGpus: 6, price: null, company: 'IronNest', line: 'Forge' },
  { id: 70, name: 'IronNest Forge F230', maxGpus: 6, price: null, company: 'IronNest', line: 'Forge' },
  { id: 71, name: 'IronNest Forge F240', maxGpus: 7, price: null, company: 'IronNest', line: 'Forge' },
  { id: 72, name: 'IronNest Forge F250', maxGpus: 8, price: null, company: 'IronNest', line: 'Forge' },
  { id: 73, name: 'IronNest Steel S300', maxGpus: 9, price: null, company: 'IronNest', line: 'Steel' },
  { id: 74, name: 'IronNest Steel S310', maxGpus: 10, price: null, company: 'IronNest', line: 'Steel' },
  { id: 75, name: 'IronNest Steel S320', maxGpus: 11, price: null, company: 'IronNest', line: 'Steel' },
  { id: 76, name: 'IronNest Steel S330', maxGpus: 12, price: null, company: 'IronNest', line: 'Steel' },
  { id: 77, name: 'IronNest Steel S340', maxGpus: 13, price: null, company: 'IronNest', line: 'Steel' },
  { id: 78, name: 'IronNest Steel S350', maxGpus: 14, price: null, company: 'IronNest', line: 'Steel' },
  { id: 79, name: 'IronNest Fortress R400', maxGpus: 15, price: null, company: 'IronNest', line: 'Fortress' },
  { id: 80, name: 'IronNest Fortress R410', maxGpus: 16, price: null, company: 'IronNest', line: 'Fortress' },
  { id: 81, name: 'IronNest Fortress R420', maxGpus: 17, price: null, company: 'IronNest', line: 'Fortress' },
  { id: 82, name: 'IronNest Fortress R430', maxGpus: 18, price: null, company: 'IronNest', line: 'Fortress' },
  { id: 83, name: 'IronNest Fortress R440', maxGpus: 19, price: null, company: 'IronNest', line: 'Fortress' },
  { id: 84, name: 'IronNest Fortress R450', maxGpus: 20, price: null, company: 'IronNest', line: 'Fortress' },
  { id: 85, name: 'IronNest Colossus C500', maxGpus: 21, price: null, company: 'IronNest', line: 'Colossus' },
  { id: 86, name: 'IronNest Colossus C510', maxGpus: 23, price: null, company: 'IronNest', line: 'Colossus' },
  { id: 87, name: 'IronNest Colossus C520', maxGpus: 25, price: null, company: 'IronNest', line: 'Colossus' },
  { id: 88, name: 'IronNest Colossus C530', maxGpus: 27, price: null, company: 'IronNest', line: 'Colossus' },
  { id: 89, name: 'IronNest Colossus C540', maxGpus: 29, price: null, company: 'IronNest', line: 'Colossus' },
  { id: 90, name: 'IronNest Colossus C550', maxGpus: 32, price: null, company: 'IronNest', line: 'Colossus' },
]

export const SUPPLIES_PRODUCTS = [
  { id: 1, name: 'Охлаждающая жидкость', price: null, category: 'cooling' },
  { id: 2, name: 'Чип для улучшения видеокарты', price: null, category: 'upgrade' },
]

export const REAL_ESTATE_PRODUCTS = [
  // Обычный
  { id: 1, name: 'Sunny Cottage', rarity: 'common', rooms: 1, tax: null, basement: 1, price: null },
  { id: 2, name: 'Green Nest', rarity: 'common', rooms: 1, tax: null, basement: 1, price: null },
  { id: 3, name: 'Little Oak', rarity: 'common', rooms: 1, tax: null, basement: 1, price: null },
  { id: 4, name: 'Rose House', rarity: 'common', rooms: 1, tax: null, basement: 2, price: null },
  { id: 5, name: 'Maple Home', rarity: 'common', rooms: 2, tax: null, basement: 2, price: null },
  { id: 6, name: 'Silver Cottage', rarity: 'common', rooms: 2, tax: null, basement: 2, price: null },
  { id: 7, name: 'Forest View', rarity: 'common', rooms: 2, tax: null, basement: 2, price: null },
  { id: 8, name: 'Pine Residence', rarity: 'common', rooms: 2, tax: null, basement: 3, price: null },
  { id: 9, name: 'Golden Nest', rarity: 'common', rooms: 2, tax: null, basement: 3, price: null },
  { id: 10, name: 'Blue Horizon', rarity: 'common', rooms: 2, tax: null, basement: 3, price: null },
  { id: 11, name: 'Stone Cottage', rarity: 'common', rooms: 2, tax: null, basement: 3, price: null },
  { id: 12, name: 'Autumn House', rarity: 'common', rooms: 2, tax: null, basement: 4, price: null },
  { id: 13, name: 'Meadow Home', rarity: 'common', rooms: 3, tax: null, basement: 4, price: null },
  { id: 14, name: 'Oak Residence', rarity: 'common', rooms: 3, tax: null, basement: 4, price: null },
  { id: 15, name: 'Cherry Cottage', rarity: 'common', rooms: 3, tax: null, basement: 4, price: null },
  { id: 16, name: 'Birch House', rarity: 'common', rooms: 3, tax: null, basement: 4, price: null },
  { id: 17, name: 'Morning Villa', rarity: 'common', rooms: 3, tax: null, basement: 5, price: null },
  { id: 18, name: 'Hill Cottage', rarity: 'common', rooms: 3, tax: null, basement: 5, price: null },
  { id: 19, name: 'River House', rarity: 'common', rooms: 3, tax: null, basement: 5, price: null },
  { id: 20, name: 'Sunset Home', rarity: 'common', rooms: 3, tax: null, basement: 5, price: null },
  // Необычный
  { id: 21, name: 'Crystal Garden', rarity: 'uncommon', rooms: 4, tax: null, basement: 6, price: null },
  { id: 22, name: 'Lake Breeze', rarity: 'uncommon', rooms: 4, tax: null, basement: 6, price: null },
  { id: 23, name: 'Amber Villa', rarity: 'uncommon', rooms: 4, tax: null, basement: 6, price: null },
  { id: 24, name: 'Willow Manor', rarity: 'uncommon', rooms: 4, tax: null, basement: 6, price: null },
  { id: 25, name: 'Mountain Rest', rarity: 'uncommon', rooms: 4, tax: null, basement: 7, price: null },
  { id: 26, name: 'Emerald Home', rarity: 'uncommon', rooms: 4, tax: null, basement: 7, price: null },
  { id: 27, name: 'Harmony House', rarity: 'uncommon', rooms: 4, tax: null, basement: 7, price: null },
  { id: 28, name: 'Royal Cottage', rarity: 'uncommon', rooms: 5, tax: null, basement: 7, price: null },
  { id: 29, name: 'Garden Estate', rarity: 'uncommon', rooms: 5, tax: null, basement: 8, price: null },
  { id: 30, name: 'Windy Hill', rarity: 'uncommon', rooms: 5, tax: null, basement: 8, price: null },
  { id: 31, name: 'Golden Villa', rarity: 'uncommon', rooms: 5, tax: null, basement: 8, price: null },
  { id: 32, name: 'Ocean View', rarity: 'uncommon', rooms: 5, tax: null, basement: 8, price: null },
  { id: 33, name: 'Snow Peak', rarity: 'uncommon', rooms: 5, tax: null, basement: 9, price: null },
  { id: 34, name: 'Silver Lake', rarity: 'uncommon', rooms: 5, tax: null, basement: 9, price: null },
  { id: 35, name: 'Crystal Peak', rarity: 'uncommon', rooms: 5, tax: null, basement: 9, price: null },
  { id: 36, name: 'Rose Manor', rarity: 'uncommon', rooms: 5, tax: null, basement: 10, price: null },
  { id: 37, name: 'Royal Garden', rarity: 'uncommon', rooms: 6, tax: null, basement: 10, price: null },
  { id: 38, name: 'Moonlight Villa', rarity: 'uncommon', rooms: 6, tax: null, basement: 10, price: null },
  { id: 39, name: 'Green Palace', rarity: 'uncommon', rooms: 6, tax: null, basement: 10, price: null },
  { id: 40, name: 'Diamond Cottage', rarity: 'uncommon', rooms: 6, tax: null, basement: 10, price: null },
  // Редкий
  { id: 41, name: 'Imperial Home', rarity: 'rare', rooms: 6, tax: null, basement: 11, price: null },
  { id: 42, name: 'Ruby Manor', rarity: 'rare', rooms: 6, tax: null, basement: 11, price: null },
  { id: 43, name: 'Forest Palace', rarity: 'rare', rooms: 6, tax: null, basement: 11, price: null },
  { id: 44, name: 'Sunrise Estate', rarity: 'rare', rooms: 6, tax: null, basement: 12, price: null },
  { id: 45, name: 'North Residence', rarity: 'rare', rooms: 7, tax: null, basement: 12, price: null },
  { id: 46, name: 'Sky House', rarity: 'rare', rooms: 7, tax: null, basement: 12, price: null },
  { id: 47, name: 'Aurora Villa', rarity: 'rare', rooms: 7, tax: null, basement: 13, price: null },
  { id: 48, name: 'Prestige Manor', rarity: 'rare', rooms: 7, tax: null, basement: 13, price: null },
  { id: 49, name: "King's Home", rarity: 'rare', rooms: 7, tax: null, basement: 13, price: null },
  { id: 50, name: 'Elite Residence', rarity: 'rare', rooms: 7, tax: null, basement: 14, price: null },
  { id: 51, name: 'Majestic Villa', rarity: 'rare', rooms: 8, tax: null, basement: 14, price: null },
  { id: 52, name: 'Royal Heights', rarity: 'rare', rooms: 8, tax: null, basement: 14, price: null },
  { id: 53, name: 'Silver Crown', rarity: 'rare', rooms: 8, tax: null, basement: 15, price: null },
  { id: 54, name: 'Golden Ridge', rarity: 'rare', rooms: 8, tax: null, basement: 15, price: null },
  { id: 55, name: 'Crimson Estate', rarity: 'rare', rooms: 8, tax: null, basement: 15, price: null },
  { id: 56, name: 'Azure Palace', rarity: 'rare', rooms: 8, tax: null, basement: 16, price: null },
  { id: 57, name: 'Ivory Manor', rarity: 'rare', rooms: 8, tax: null, basement: 16, price: null },
  // Эпический
  { id: 58, name: 'Stormwatch Villa', rarity: 'epic', rooms: 9, tax: null, basement: 16, price: null },
  { id: 59, name: 'Dragonspire House', rarity: 'epic', rooms: 9, tax: null, basement: 17, price: null },
  { id: 60, name: 'Obsidian Hall', rarity: 'epic', rooms: 9, tax: null, basement: 17, price: null },
  { id: 61, name: 'Titan Crest', rarity: 'epic', rooms: 9, tax: null, basement: 18, price: null },
  { id: 62, name: 'Eclipse Estate', rarity: 'epic', rooms: 9, tax: null, basement: 18, price: null },
  { id: 63, name: 'Starforge Manor', rarity: 'epic', rooms: 9, tax: null, basement: 18, price: null },
  { id: 64, name: 'Celestial Home', rarity: 'epic', rooms: 10, tax: null, basement: 19, price: null },
  { id: 65, name: 'Nightfall Villa', rarity: 'epic', rooms: 10, tax: null, basement: 19, price: null },
  { id: 66, name: 'Thunder Peak', rarity: 'epic', rooms: 10, tax: null, basement: 20, price: null },
  { id: 67, name: 'Phoenix Residence', rarity: 'epic', rooms: 10, tax: null, basement: 20, price: null },
  { id: 68, name: 'Ironwind Estate', rarity: 'epic', rooms: 10, tax: null, basement: 20, price: null },
  { id: 69, name: 'Lunar Fortress', rarity: 'epic', rooms: 10, tax: null, basement: 21, price: null },
  { id: 70, name: 'Solar Mansion', rarity: 'epic', rooms: 10, tax: null, basement: 21, price: null },
  // Легендарный
  { id: 71, name: 'Astral Palace', rarity: 'legendary', rooms: 11, tax: null, basement: 21, price: null },
  { id: 72, name: 'Void Castle', rarity: 'legendary', rooms: 11, tax: null, basement: 22, price: null },
  { id: 73, name: 'Infinity House', rarity: 'legendary', rooms: 11, tax: null, basement: 22, price: null },
  { id: 74, name: 'Nebula Citadel', rarity: 'legendary', rooms: 11, tax: null, basement: 22, price: null },
  { id: 75, name: 'Quantum Villa', rarity: 'legendary', rooms: 12, tax: null, basement: 23, price: null },
  { id: 76, name: 'Godfall Residence', rarity: 'legendary', rooms: 12, tax: null, basement: 23, price: null },
  { id: 77, name: 'Eternal Palace', rarity: 'legendary', rooms: 12, tax: null, basement: 24, price: null },
  { id: 78, name: 'Supreme Nexus', rarity: 'legendary', rooms: 12, tax: null, basement: 24, price: null },
  { id: 79, name: 'Hyperion Tower Home', rarity: 'legendary', rooms: 12, tax: null, basement: 24, price: null },
  { id: 80, name: 'Omega Estate', rarity: 'legendary', rooms: 12, tax: null, basement: 24, price: null },
  { id: 81, name: 'Final Crown House', rarity: 'legendary', rooms: 12, tax: null, basement: 24, price: null },
]

export const BUSINESS_PRODUCTS = [
  { id: 1, name: 'Pixel Store', category: 'retail', price: null, income: null },
  { id: 2, name: 'GPU Market', category: 'tech', price: null, income: null },
  { id: 3, name: 'CoreTech Shop', category: 'tech', price: null, income: null },
  { id: 4, name: 'Neon Hardware', category: 'tech', price: null, income: null },
  { id: 5, name: 'Quantum GPUs', category: 'tech', price: null, income: null },
  { id: 6, name: 'Street Kiosk', category: 'retail', price: null, income: null },
  { id: 7, name: 'Mini Market', category: 'retail', price: null, income: null },
  { id: 8, name: 'Urban Shop', category: 'retail', price: null, income: null },
  { id: 9, name: 'Fashion Store', category: 'retail', price: null, income: null },
  { id: 10, name: 'Tech Repair', category: 'service', price: null, income: null },
  { id: 11, name: 'Overclock Lab', category: 'service', price: null, income: null },
  { id: 12, name: 'Crypto Office', category: 'office', price: null, income: null },
]

